controle_estoque/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from estoque import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='login/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='login/logout.html'), name='logout'),
    path('register/', views.register, name='cadastro'),
    path('', include('estoque.urls')),
]

estoque/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    #path("",,name="home")
    path("",home,name="home"),
    #Produtos
    path("Produtos/",Listar_Produtos.as_view(),name="Listar_produtos"),
    path("Produtos/Cadastro",Criar_Produto.as_view(),name="Cadastro_produto"),
    path("Produtos/Editar/<int:pk>/",Atualizar_Produto.as_view(),name="Editar_produto"),
    path("Produtos/Excluir/<int:pk>/",Deletar_Produto.as_view(),name="Deletar_produto"),
    path("Produtos/Detalhes/<int:pk>/",detalhes_produto,name="Detalhes_produto"),
    path('Produtos/Entrada/<int:pk>/', registrar_entrada, name='registrar_entrada'),
    path('Produtos/Saida/<int:pk>/', registrar_saida, name='registrar_saida'),
    path('Produtos/Historico/Entradas/', listar_entradas, name='listar_entradas'),
    path('Produtos/Historico/Saidas/', listar_saidas, name='listar_saidas'),

    #Fornecedores
    path("Fornecedores/",Listar_Fornecedores.as_view(),name="Listar_fornecedores"),
    path("Fornecedores/Cadastro",Criar_Fornecedor.as_view(),name="Cadastro_fornecedor"),
    path("Fornecedores/Excluir/<int:pk>/",Deletar_Fornecedor.as_view(),name="Deletar_fornecedor"),
    path("Fornecedores/Editar/<int:pk>/",Atualizar_Fornecedor.as_view(),name="Editar_fornecedor"),
    path("Fornecedores/Detalhes/<int:pk>/",detalhes_fornecedor,name="Detalhes_fornecedor"),

    
    #Clientes
    path("Clientes/", Listar_Clientes.as_view(), name="Listar_clientes"),
    path("Clientes/Cadastro", Criar_Cliente.as_view(), name="Cadastro_cliente"),
    path("Clientes/Excluir/<int:pk>/", Deletar_Cliente.as_view(), name="Deletar_cliente"),
    path("Clientes/Editar/<int:pk>/", Atualizar_Cliente.as_view(), name="Editar_cliente"),
    path("Clientes/Detalhes/<int:pk>/", detalhes_cliente, name="Detalhes_cliente"),
]   

estoque/models.py
from django.db import models

# Create your models here.

class Fornecedor(models.Model):

    nome = models.CharField(max_length=100)
    telefone = models.CharField(max_length=25,blank=True)
    email = models.EmailField(blank=True)
    resumo = models.TextField(blank=True)

    class Meta:
        verbose_name = "Fornecedor"
        verbose_name_plural = "Fornecedores"

    def __str__(self):
        return self.nome
    
class Cliente(models.Model):

    nome = models.CharField(max_length=100)
    telefone = models.CharField(max_length=25,blank=True)
    email = models.EmailField(blank=True)

    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"

    def __str__(self):
        return self.nome

    
class Produto(models.Model):

    nome = models.CharField(max_length=100)
    fornecedor = models.ForeignKey(Fornecedor, on_delete=models.CASCADE)
    quantidade = models.IntegerField()
    valor_compra = models.FloatField()
    valor_venda = models.FloatField()
    descricao = models.TextField(blank=True)

    def __str__(self):
        return self.nome

class Entrada(models.Model):
    produto = models.ForeignKey(Produto,on_delete=models.CASCADE)
    quantidade = models.IntegerField()
    data = models.DateTimeField(auto_now_add=True)

class Saida(models.Model):
    produto = models.ForeignKey(Produto,on_delete=models.CASCADE)
    quantidade = models.IntegerField()
    cliente = models.ForeignKey(Cliente,on_delete=models.CASCADE)
    data = models.DateTimeField(auto_now_add=True)



estoque/forms.py
from django import forms 
from .models import Produto,Entrada,Saida,Fornecedor
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class FornecedorForm(forms.ModelForm):
    class Meta:
        model = Fornecedor
        fields = ["nome","telefone","email","resumo"]

class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = ["nome","fornecedor","quantidade","valor_compra","valor_venda","descricao"]


class EntradaForm(forms.ModelForm):
    class Meta:
        model = Entrada
        fields = ["quantidade"]

class SaidaForm(forms.ModelForm):
    class Meta:
        model = Saida
        fields = ["quantidade","cliente"]



class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

estoque/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Fornecedor,Produto,Entrada,Saida,Cliente
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from .forms import EntradaForm,SaidaForm
from django.contrib import messages
from .forms import UserRegisterForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.db.models import Q

def home(request):
    return render(request,"index.html")


#Criação de conta
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            login(request, user)
            return redirect('home')
    else:
        form = UserRegisterForm()
    return render(request, 'login/cadastro.html', {'form': form})


#Clientes

class Listar_Clientes(LoginRequiredMixin,ListView):
    model = Cliente
    template_name = "clientes/listar_clientes.html"
    context_object_name = "clientes"
    def get_queryset(self):
        queryset = super().get_queryset()
        search_term = self.request.GET.get('q', '')  # Pega o termo de pesquisa, padrão é uma string vazia
        
        if search_term:
            queryset = queryset.filter(
                Q(nome__icontains=search_term) |  # Filtra pelo nome do produto
                Q(email__icontains=search_term)  # Filtra pela descrição do produto (opcional)
            )
        
        return queryset

class Criar_Cliente(LoginRequiredMixin,CreateView):
    model = Cliente
    template_name = "clientes/cliente_form.html"
    fields = ["nome", "telefone", "email"]
    success_url = reverse_lazy("Listar_clientes")


class Atualizar_Cliente(LoginRequiredMixin,UpdateView):
    model = Cliente
    template_name = "clientes/cliente_form.html"
    fields = ["nome", "telefone", "email"]
    success_url = reverse_lazy("Listar_clientes")


class Deletar_Cliente(LoginRequiredMixin,DeleteView):
    model = Cliente
    template_name = "clientes/deletar_cliente.html"
    success_url = reverse_lazy("Listar_clientes")

@login_required
def detalhes_cliente(request, pk):
    cliente = get_object_or_404(Cliente, pk=pk)
    return render(request, "clientes/cliente_detalhes.html", {"cliente": cliente})



#Fornecedores


class Listar_Fornecedores(LoginRequiredMixin,ListView):
    model = Fornecedor
    template_name = "fornecedores/listar_fornecedores.html"
    context_object_name = "fornecedores"
    def get_queryset(self):
        queryset = super().get_queryset()
        search_term = self.request.GET.get('q', '')  # Pega o termo de pesquisa, padrão é uma string vazia
        
        if search_term:
            queryset = queryset.filter(
                Q(nome__icontains=search_term) |  # Filtra pelo nome do produto
                Q(resumo__icontains=search_term)  # Filtra pela descrição do produto (opcional)
            )
        
        return queryset

class Criar_Fornecedor(LoginRequiredMixin,CreateView):
    model = Fornecedor
    template_name = "fornecedores/fornecedor_form.html"
    fields = ["nome", "telefone", "email", "resumo"]
    success_url = reverse_lazy("Listar_fornecedores")


class Atualizar_Fornecedor(LoginRequiredMixin,UpdateView):
    model = Fornecedor
    template_name = "fornecedores/fornecedor_form.html"
    fields = ["nome", "telefone", "email", "resumo"]
    success_url = reverse_lazy("Listar_fornecedores")


class Deletar_Fornecedor(LoginRequiredMixin,DeleteView):
    model = Fornecedor
    template_name = "fornecedores/deletar_fornecedor.html"
    success_url = reverse_lazy("Listar_fornecedores")

@login_required
def detalhes_fornecedor(request, pk):
    fornecedor = get_object_or_404(Fornecedor, pk=pk)
    return render(request, "fornecedores/fornecedor_detalhes.html", {"fornecedor": fornecedor})

#Produtos

class Listar_Produtos(LoginRequiredMixin,ListView):
    model = Produto
    template_name = "estoque/produtos_list.html"
    context_object_name = "produtos"

    def get_queryset(self):
        queryset = super().get_queryset()
        search_term = self.request.GET.get('q', '')  # Pega o termo de pesquisa, padrão é uma string vazia
        
        if search_term:
            queryset = queryset.filter(
                Q(nome__icontains=search_term) |  # Filtra pelo nome do produto
                Q(descricao__icontains=search_term)  # Filtra pela descrição do produto (opcional)
            )
        
        return queryset
        
class Criar_Produto(LoginRequiredMixin,CreateView):
    model = Produto
    template_name = "estoque/produto_form.html"
    fields = ["nome","fornecedor","quantidade","valor_compra","valor_venda","descricao"]
    success_url=reverse_lazy("Listar_produtos")


class Atualizar_Produto(LoginRequiredMixin,UpdateView):
    model = Produto
    template_name = "estoque/produto_form.html"
    fields = ["nome","fornecedor","quantidade","valor_compra","valor_venda","descricao"]
    success_url = reverse_lazy("Listar_produtos")


class Deletar_Produto(LoginRequiredMixin,DeleteView):
    model = Produto
    template_name = "estoque/deletar_produto.html"
    success_url = reverse_lazy("Listar_produtos")

@login_required
def detalhes_produto(request,pk):
    produto = get_object_or_404(Produto,pk=pk)
    return render(request,"estoque/produtos_detalhes.html",{"produto":produto})

@login_required
def registrar_entrada(request, pk):
    produto = get_object_or_404(Produto, pk=pk)
    if request.method == 'POST':
        form = EntradaForm(request.POST)
        if form.is_valid():
            entrada = form.save(commit=False)
            entrada.produto = produto
            entrada.save()
            produto.quantidade += entrada.quantidade
            produto.save()
            return redirect('Listar_produtos')
    else:
        form = EntradaForm()
    return render(request, 'estoque/entrada_produto.html', {'form': form, 'produto': produto})

@login_required
def registrar_saida(request, pk):
    produto = get_object_or_404(Produto, pk=pk)
    if request.method == 'POST':
        form = SaidaForm(request.POST)
        if form.is_valid():
            saida = form.save(commit=False)
            saida.produto = produto
            if produto.quantidade >= saida.quantidade:
                saida.save()
                produto.quantidade -= saida.quantidade
                produto.save()
                return redirect('Listar_produtos')
            else:
                form.add_error('quantidade', 'Quantidade insuficiente em estoque.')
    else:
        form = SaidaForm()
    return render(request, 'estoque/saida_produto.html', {'form': form, 'produto': produto})

@login_required
def listar_entradas(request):
    query = request.GET.get('q')
    if query:
        entradas = Entrada.objects.filter(produto__nome__icontains=query).order_by('-data')
    else:
        entradas = Entrada.objects.all().order_by('-data')
    return render(request, 'estoque/listar_entradas.html', {'entradas': entradas})

@login_required
def listar_saidas(request):
    query = request.GET.get('q')
    if query:
        saidas = Saida.objects.filter(produto__nome__icontains=query).order_by('-data')
    else:
        saidas = Saida.objects.all().order_by('-data')
    return render(request, 'estoque/listar_saidas.html', {'saidas': saidas})

estoque/templates/estoque/deletar_produto.html
{% extends "base.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Excluir Produto</title>

</head>
<body>
    {% block content  %}
    <div class="container">
        <h1>Excluir Produto</h1>
        <p>Tem certeza que deseja excluir o produto <strong>{{ object.nome }}</strong>?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Excluir</button>
            <a href="{% url 'Listar_produtos' %}" class="btn btn-secondary">Cancelar</a>
        </form>
    </div>
</body>
{% endblock content  %}
</html>

estoque/templates/estoque/entrada_produto.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h2>Registrar Entrada de Produto: {{ produto.nome }}</h2>
    <h2>Quantidade em estoque:{{produto.quantidade}}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Registrar Entrada</button>
    </form>
</div>
{% endblock content %}

estoque/templates/estoque/listar_entradas.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h2>Lista de Entradas</h2>
    <center>
    <form class="search-form" method="get" action="{% url 'listar_entradas' %}">
        <input class="search-input" type="text" name="q" placeholder="Pesquisar por produto" value="{{ request.GET.q }}">
        <button class="search-button" type="submit">Pesquisar</button>
      </form>
    </center>
    <table>
        <thead>
            <tr>
                <th>Produto</th>
                <th>Quantidade</th>
                <th>Data</th>
            </tr>
        </thead>
        <tbody>
            {% for entrada in entradas %}
            <tr>
                <td>{{ entrada.produto.nome }}</td>
                <td>{{ entrada.quantidade }}</td>
                <td>{{ entrada.data }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">Nenhuma entrada registrada.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'Listar_produtos' %}" class="btn btn-secondary">Voltar</a>
</div>
{% endblock content %}

estoque/templates/estoque/listar_saidas.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h2>Lista de Saídas</h2>
    <form class="search-form" method="get" action="{% url 'listar_saidas' %}">
        <input class="search-input" type="text" name="q" placeholder="Pesquisar por produto" value="{{ request.GET.q }}">
        <button class="search-button" type="submit">Pesquisar</button>
      </form>
    <table>
        <thead>
            <tr>
                <th>Produto</th>
                <th>Quantidade</th>
                <th>Cliente</th>
                <th>Data</th>
            </tr>
        </thead>
        <tbody>
            {% for saida in saidas %}
            <tr>
                <td>{{ saida.produto.nome }}</td>
                <td>{{ saida.quantidade }}</td>
                <td>{{ saida.cliente }}</td>
                <td>{{ saida.data }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">Nenhuma saída registrada.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'Listar_produtos' %}" class="btn btn-secondary">Voltar</a>
</div>
{% endblock content %}

estoque/templates/estoque/produto_form.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <form method="post" class="form-container">
        <h2 class="form-title">Editar ou Adicionar Novo Produto</h2>
        {% csrf_token %}
    
        <div class="form-group">
            <label for="id_nome">Nome</label>
            {{ form.nome }}
        </div>
    
        <div class="form-group">
            <label for="id_fornecedor">Fornecedor</label>
            {{ form.fornecedor }}
        </div>
    
        <div class="form-group">
            <label for="id_quantidade">Quantidade</label>
            {{ form.quantidade }}
        </div>
    
        <div class="form-group">
            <label for="id_valor_compra">Valor de compra</label>
            {{ form.valor_compra }}
        </div>

        <div class="form-group">
            <label for="id_valor_venda">Valor de venda</label>
            {{ form.valor_venda }}
        </div>

        <div class="form-group">
            <label for="id_descricao">Descrição</label>
            {{ form.descricao }}
        </div>
    
        <div class="form-buttons">
            <button class="btn btn-primary" type="submit">Salvar</button>
            <a href="{% url 'Listar_produtos' %}" class="btn btn-secondary">Cancelar</a>
        </div>
    </form>
</div>

{% endblock content %}

estoque/templates/estoque/produtos_detalhes.html
{% extends "base.html" %}

{% block content %}
<center>
<div class="container">
    <h2 class="page-title">Detalhes do produto</h2>

    <div class="detail-group">
        <p class="detail-title">Nome:</p>
        <p class="detail-content">{{ produto.nome }}</p>
    </div>

    <div class="detail-group">
        <p class="detail-title">Fornecedor:</p>
        <p class="detail-content">{{ produto.fornecedor }}</p>
    </div>

    <div class="detail-group">
        <p class="detail-title">Quantidade:</p>
        <p class="detail-content">{{ produto.quantidade }}</p>
    </div>

    <div class="detail-group">
        <p class="detail-title">Valor de compra:</p>
        <p class="detail-content">R$ {{ produto.valor_compra }}</p>
    </div>

    <div class="detail-group">
        <p class="detail-title">Valor de venda:</p>
        <p class="detail-content">R$ {{ produto.valor_venda }}</p>
    </div>

    <div class="detail-group">
        <p class="detail-title">Descrição:</p>
        {% if produto.descricao == "" %}
        <p class="detail-content">Nenhuma descrição adicionada.</p>
        {% else %}
        <p class="detail-content">{{ produto.descricao }}</p>
        {% endif %}
        
    </div>

    <a href="{% url 'Listar_produtos' %}" class="btn btn-secondary">Voltar</a>
</div>
</center>
{% endblock content %}

estoque/templates/estoque/produtos_list.html
{% extends "base.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title  %} Produtos {% endblock title  %}</title>

</head>
<body>
    {% block content %}

    <table>
        <caption>Produtos</caption>
        <caption class="cadastrar-produto"><a class="cadastrar-produto" href="{% url "Cadastro_produto" %}">Cadastrar novo produto</a></caption>
        
        <center>
        <form class="search-form" method="get" action="{% url 'Listar_produtos' %}">
            <input type="text" name="q" placeholder="Pesquisar produtos" value="{{ request.GET.q }}" class="search-input">
            <button type="submit" class="search-button">Pesquisar</button>
        </form>
    </center>
        <thead>
            <tr>
                <th class="titulo-tabela">Nome</th>
                <th class="titulo-tabela">Fornecedor</th>
                <th class="titulo-tabela">Quantidade</th>
                <th class="titulo-tabela">Valor de compra</th>
                <th class="titulo-tabela">Valor de venda</th>
                <th class="titulo-tabela">Ações</th>
                <th class="titulo-tabela">Estoque</th>
               
            </tr>
        </thead>
        <tbody>
            {% for produto in produtos %}
            <tr>
                <td class="campo" data-label="Nome"><a class="nome" href="{% url "Detalhes_produto" produto.pk %}">{{ produto.nome }}</a></td>
                <td class="campo" data-label="Fornecedor">{{ produto.fornecedor }}</td>
                <td class="campo" data-label="Quantidade">{{ produto.quantidade }}</td>
                <td class="campo" data-label="Valor de compra">R$ {{ produto.valor_compra }}</td>
                <td class="campo" data-label="Valor de venda">R$ {{ produto.valor_venda }}</td>
                <td class="campo" data-label="Ações">
                    <a class="a-editar" href="{% url "Editar_produto" produto.pk %}">Editar</a>
                    <a class="a-excluir" href="{% url "Deletar_produto" produto.pk %}">Excluir</a>
                </td>
                <td class="campo" data-label="Estoque">
                    <a class="a-editar" href="{% url "registrar_entrada" produto.pk %}">Entrada</a>
                    <a class="a-excluir" href="{% url "registrar_saida" produto.pk %}">Saida</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">Nenhum produto encontrado.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endblock content %}
</body>
</html>

estoque/templates/estoque/saida_produto.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h2>Registrar Saída de Produto: {{ produto.nome }}</h2>
    <h2>Quantidade em estoque:{{produto.quantidade}}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Registrar Saída</button>
    </form>
</div>
{% endblock content %}